unbind C-b
set -g prefix `
bind -n C-k clear-history
bind-key ` last-window
bind-key e send-prefix
setw -gq utf8 on

set -g history-limit 10000

# set shell
set -g default-shell /usr/bin/zsh

# List of plugins
set -g @tpm_plugins '          \
  tmux-plugins/tpm             \
  tmux-plugins/tmux-sensible   \
  tmux-plugins/tmux-resurrect  \
'

 set-option -g @ssh-split-fail "false"
 set-option -g @ssh-split-no-shell "false"
 set-option -g @ssh-split-verbose "true"
 set-option -g @ssh-split-h-key "|"
 set-option -g @ssh-split-v-key "S"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'jimeh/tmux-themepack'
#set -g @themepack 'powerline/block/green_gray_custom'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-sidebar'
set -g @plugin 'tmux-plugins/tmux-sessionist'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-cowboy'
set -g @plugin 'tmux-plugins/tmux-fpp'
set -g @plugin 'jaclu/tmux-power-zoom'
set -g @plugin 'jaclu/tmux-menus'
set -g @plugin 'pschmitt/tmux-ssh-split'

###############
# pane border #
###############
#set -g pane-border-status bottom
set -g pane-border-status off
#colors for pane borders
setw -g pane-border-style fg=green,bg=black
setw -g pane-active-border-style fg=colour118,bg=black
setw -g automatic-rename off
setw -g pane-border-format ' #{pane_index} #{pane_title} : #{pane_current_path} '
# active pane normal, other shaded out​
setw -g window-style fg=colour28,bg=colour16
setw -g window-active-style fg=colour46,bg=colour16

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

set -g mouse on
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -se c -i"
bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -se c -i"
#set -g mouse-select-pane on
bind -n S-right select-pane -t :.+
bind -n S-left select-pane -t :.-

set -g status-bg "#666400"

set -g default-terminal "screen-256color"
#set -g status-utf8 on
